-- Create request_logs table for LiteLLM logging integration
create table if not exists public.request_logs (
  id bigint generated by default as identity,
  created_at timestamp with time zone null default now(),
  model text null default ''::text,
  messages json null default '{}'::json,
  response json null default '{}'::json,
  end_user text null default ''::text,
  status text null default ''::text,
  error json null default '{}'::json,
  response_time real null default '0'::real,
  total_cost real null,
  additional_details json null default '{}'::json,
  litellm_call_id text unique,
  primary key (id)
);
